@extends('layouts.main')

@section('title', 'AI Face Value Analysis')

@section('content')
<div class="container-fluid px-0">
    <!-- Page Header -->
    <div class="mb-4">
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
            <div>
                <h1 class="h3 mb-2" style="background: linear-gradient(135deg, #10b981, #3b82f6); -webkit-background-clip: text; background-clip: text; color: transparent;">
                    AI Face Value Analysis
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}" style="color: #10b981;">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('supervisorfacevalues.index') }}" style="color: #10b981;">Face Values</a></li>
                        <li class="breadcrumb-item active" style="color: #6b7280;">AI Analysis</li>
                    </ol>
                </nav>
                <p class="text-muted mt-2 mb-0">AI-powered analysis of face value allocation trends and patterns</p>
            </div>
            <div class="d-flex gap-2">
                <a href="{{ route('supervisorfacevalues.index') }}" class="btn-outline-modern">
                    <i class="bi bi-arrow-left me-2"></i>Back to Face Values
                </a>
            </div>
        </div>
    </div>

    <!-- Analysis Results Card -->
    <div class="modern-card">
        <div class="card-header bg-transparent border-bottom p-4" style="border-color: rgba(16, 185, 129, 0.15);">
            <div class="d-flex align-items-center gap-2">
                <div class="stat-icon-sm">
                    <i class="bi bi-robot" style="color: #10b981;"></i>
                </div>
                <h5 class="mb-0 fw-semibold">AI Analysis Report</h5>
                <span class="badge ms-2" style="background: linear-gradient(135deg, #10b981, #3b82f6);">Powered by AI</span>
            </div>
        </div>
        <div class="card-body p-4">
            <div class="alert alert-info mb-4">
                <i class="bi bi-info-circle-fill me-2"></i>
                This analysis was generated by AI based on your face value allocation data. Please review for accuracy.
            </div>
            
            <div class="analysis-content bg-light p-4 rounded" style="white-space: pre-wrap; line-height: 1.8; font-family: 'Inter', sans-serif;">
                {!! nl2br(e($analysis)) !!}
            </div>
            
            <div class="mt-4 d-flex gap-3">
                <button onclick="window.print()" class="btn-outline-modern">
                    <i class="bi bi-printer me-1"></i>Print Report
                </button>
                <a href="{{ route('supervisorfacevalues.index') }}" class="btn-outline-modern">
                    <i class="bi bi-arrow-left me-1"></i>Back
                </a>
            </div>
        </div>
    </div>

    <!-- Supporting Data Card -->
    <div class="modern-card mt-4">
        <div class="card-header bg-transparent border-bottom p-4" style="border-color: rgba(16, 185, 129, 0.15);">
            <h5 class="mb-0 fw-semibold">
                <i class="bi bi-table me-2" style="color: #10b981;"></i>
                Supporting Data
            </h5>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-modern mb-0">
                    <thead>
                        <tr>
                            <th>Clerk Name</th>
                            <th>Allocated</th>
                            <th>Used</th>
                            <th>Spoiled</th>
                            <th>Usage Rate</th>
                        </thead>
                        <tbody>
                            @foreach($clerks as $clerk)
                            <tr>
                                <td class="fw-medium">
                                    <i class="bi bi-person-circle me-2" style="color: #10b981;"></i>
                                    {{ $clerk['name'] }}
                                
                                
                                <td class="text-end">{{ number_format($clerk['allocated']) }}
                                
                                <td class="text-end text-warning">{{ number_format($clerk['used']) }}
                                
                                <td class="text-end text-danger">{{ number_format($clerk['spoiled']) }}
                                
                                <td class="text-end">
                                    @php
                                        $usageRate = $clerk['allocated'] > 0 ? ($clerk['used'] / $clerk['allocated']) * 100 : 0;
                                    @endphp
                                    <div class="progress" style="height: 8px; width: 100px;">
                                        <div class="progress-bar" role="progressbar" style="width: {{ $usageRate }}%; background: linear-gradient(135deg, #10b981, #3b82f6);" aria-valuenow="{{ $usageRate }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small class="text-muted">{{ round($usageRate, 1) }}%</small>
                                
                              
                            @endforeach
                        </tbody>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@push('styles')
<style>
    .stat-icon-sm {
        width: 36px;
        height: 36px;
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.1), rgba(59, 130, 246, 0.1));
        border-radius: 0.75rem;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    
    .analysis-content {
        background: linear-gradient(135deg, #f9fafb, #ffffff);
        border: 1px solid #e5e7eb;
        border-radius: 1rem;
    }
    
    .analysis-content p {
        margin-bottom: 0.75rem;
    }
    
    .analysis-content ul, .analysis-content ol {
        margin-top: 0.5rem;
        margin-bottom: 0.75rem;
        padding-left: 1.5rem;
    }
    
    .analysis-content li {
        margin-bottom: 0.25rem;
    }
    
    .progress {
        background-color: #e5e7eb;
        border-radius: 1rem;
        overflow: hidden;
    }
    
    @media print {
        .btn-outline-modern, .alert-info, .card-header .d-flex .badge {
            display: none;
        }
        
        .analysis-content {
            background: white;
            border: none;
        }
        
        .modern-card {
            box-shadow: none;
            border: 1px solid #e5e7eb;
        }
    }
</style>
@endpush
@endsection