@extends('layouts.main')

@section('title', 'AI Report Summary')

@section('content')
<div class="container-fluid px-0">
    <div class="mb-4">
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
            <div>
                <h1 class="h3 mb-2" style="background: linear-gradient(135deg, #10b981, #3b82f6); -webkit-background-clip: text; background-clip: text; color: transparent;">
                    AI Report Summary
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}" style="color: #10b981;">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('ai.analytics') }}" style="color: #10b981;">AI Analytics</a></li>
                        <li class="breadcrumb-item active" style="color: #6b7280;">Report Summary</li>
                    </ol>
                </nav>
                <p class="text-muted mt-2 mb-0">AI-powered analysis and insights from your collection data</p>
            </div>
            <div class="d-flex gap-2">
                <button class="btn-modern" onclick="downloadPDF()">
                    <i class="bi bi-file-pdf me-2"></i>Download PDF
                </button>
                <button class="btn-outline-modern" onclick="window.print()">
                    <i class="bi bi-printer me-2"></i>Print
                </button>
            </div>
        </div>
    </div>

    <div class="modern-card" id="reportContent">
        <div class="card-header bg-transparent border-bottom p-4" style="background: linear-gradient(135deg, rgba(16, 185, 129, 0.05), rgba(59, 130, 246, 0.05));">
            <div class="d-flex justify-content-between align-items-center flex-wrap gap-2">
                <div>
                    <h5 class="mb-0 fw-semibold">
                        <i class="bi bi-robot me-2" style="color: #10b981;"></i>
                        AI Analysis Report
                    </h5>
                    <small class="text-muted">Generated on {{ now()->format('F j, Y \a\t g:i A') }}</small>
                </div>
                <div class="d-flex gap-2">
                    <span class="badge" style="background: linear-gradient(135deg, #10b981, #3b82f6); color: white; padding: 0.5rem 1rem;">
                        <i class="bi bi-stars me-1"></i>AI Generated
                    </span>
                </div>
            </div>
        </div>
        <div class="card-body p-4">
            <div class="alert alert-modern alert-info mb-4">
                <div class="d-flex align-items-center gap-2">
                    <i class="bi bi-info-circle-fill fs-5" style="color: #10b981;"></i>
                    <div>
                        <strong>AI Disclaimer</strong><br>
                        <small>This summary was generated by artificial intelligence. Please review for accuracy and use as a reference alongside your manual analysis.</small>
                    </div>
                </div>
            </div>
            
            <div id="aiSummaryContent" class="ai-summary-content p-4 rounded" style="background: linear-gradient(135deg, #ffffff, #f8fafc); border: 1px solid rgba(16, 185, 129, 0.2); line-height: 1.8;">
                {!! $summary !!}
            </div>
            
            <div class="mt-4 pt-3 border-top d-flex justify-content-between align-items-center flex-wrap gap-3">
                <div>
                    <small class="text-muted">
                        <i class="bi bi-shield-check me-1" style="color: #10b981;"></i>
                        Report ID: AI-{{ date('YmdHis') }}
                    </small>
                </div>
                <div class="d-flex gap-2">
                    <a href="{{ url()->previous() }}" class="btn-outline-modern">
                        <i class="bi bi-arrow-left me-1"></i>Back
                    </a>
                    <button onclick="shareReport()" class="btn-outline-modern">
                        <i class="bi bi-share me-1"></i>Share
                    </button>
                    <button onclick="copyToClipboard()" class="btn-outline-modern">
                        <i class="bi bi-copy me-1"></i>Copy
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

@push('styles')
<style>
    .alert-modern {
        border: none;
        border-radius: 1rem;
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.1), rgba(59, 130, 246, 0.05));
        padding: 1rem 1.5rem;
    }
    
    .ai-summary-content {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
    
    .ai-summary-content h1, 
    .ai-summary-content h2, 
    .ai-summary-content h3 {
        color: #10b981;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
        font-weight: 600;
    }
    
    .ai-summary-content h1:first-child,
    .ai-summary-content h2:first-child,
    .ai-summary-content h3:first-child {
        margin-top: 0;
    }
    
    .ai-summary-content p {
        margin-bottom: 1rem;
        color: #374151;
    }
    
    .ai-summary-content ul, 
    .ai-summary-content ol {
        margin-left: 1.5rem;
        margin-bottom: 1rem;
    }
    
    .ai-summary-content li {
        margin-bottom: 0.5rem;
        color: #4b5563;
    }
    
    .ai-summary-content .stat-box {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.08), rgba(59, 130, 246, 0.08));
        padding: 1.25rem;
        border-radius: 1rem;
        margin: 1.5rem 0;
        border-left: 4px solid #10b981;
    }
    
    .ai-summary-content .warning-box {
        background: linear-gradient(135deg, rgba(245, 158, 11, 0.08), rgba(245, 158, 11, 0.03));
        padding: 1.25rem;
        border-radius: 1rem;
        margin: 1.5rem 0;
        border-left: 4px solid #f59e0b;
    }
    
    .ai-summary-content .success-box {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.1), rgba(16, 185, 129, 0.05));
        padding: 1.25rem;
        border-radius: 1rem;
        margin: 1.5rem 0;
        border-left: 4px solid #10b981;
    }
    
    .ai-summary-content table {
        width: 100%;
        border-collapse: collapse;
        margin: 1rem 0;
    }
    
    .ai-summary-content th {
        background: linear-gradient(135deg, #10b981, #3b82f6);
        color: white;
        padding: 0.75rem;
        text-align: left;
    }
    
    .ai-summary-content td {
        padding: 0.75rem;
        border-bottom: 1px solid #e5e7eb;
    }
    
    .ai-summary-content tr:hover {
        background: rgba(16, 185, 129, 0.05);
    }
    
    .btn-modern {
        background: linear-gradient(135deg, #10b981, #3b82f6);
        border: none;
        padding: 0.625rem 1.5rem;
        border-radius: 2rem;
        color: white;
        font-weight: 500;
        transition: all 0.2s ease;
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
    }
    
    .btn-modern:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);
        color: white;
    }
    
    .btn-outline-modern {
        background: transparent;
        border: 1.5px solid #10b981;
        padding: 0.625rem 1.5rem;
        border-radius: 2rem;
        color: #059669;
        font-weight: 500;
        transition: all 0.2s ease;
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        text-decoration: none;
    }
    
    .btn-outline-modern:hover {
        background: linear-gradient(135deg, #10b981, #3b82f6);
        border-color: transparent;
        color: white;
        transform: translateY(-1px);
        text-decoration: none;
    }
    
    /* Print Styles */
    @media print {
        .btn-modern, 
        .btn-outline-modern,
        nav,
        .breadcrumb,
        .alert-modern,
        .border-top {
            display: none !important;
        }
        
        .modern-card {
            box-shadow: none;
            border: 1px solid #e5e7eb;
            margin: 0;
            padding: 0;
        }
        
        .ai-summary-content {
            background: white !important;
            color: black !important;
        }
        
        body {
            background: white;
        }
    }
</style>
@endpush

@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function downloadPDF() {
        const element = document.getElementById('reportContent');
        const originalContent = element.innerHTML;
        
        // Add header for PDF
        const header = `
            <div style="text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #10b981;">
                <h1 style="color: #10b981; margin-bottom: 10px;">AI Report Summary</h1>
                <p style="color: #6b7280;">Generated on ${new Date().toLocaleString()}</p>
                <p style="color: #6b7280;">Report ID: AI-${new Date().toISOString().slice(0,19).replace(/:/g, '')}</p>
            </div>
        `;
        
        // Add footer for PDF
        const footer = `
            <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;">
                <p>This report was generated by AI. For support, contact your system administrator.</p>
                <p>Page 1 of 1</p>
            </div>
        `;
        
        // Temporarily modify content for PDF
        element.innerHTML = header + originalContent + footer;
        
        const opt = {
            margin: [0.5, 0.5, 0.5, 0.5],
            filename: `AI_Report_Summary_${new Date().toISOString().slice(0,19).replace(/:/g, '-')}.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true, letterRendering: true },
            jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
        };
        
        html2pdf().set(opt).from(element).save().then(() => {
            // Restore original content
            element.innerHTML = originalContent;
        }).catch(error => {
            console.error('PDF generation error:', error);
            element.innerHTML = originalContent;
            alert('Error generating PDF. Please try again.');
        });
    }
    
    function shareReport() {
        const content = document.getElementById('aiSummaryContent').innerText;
        const shareData = {
            title: 'AI Report Summary',
            text: content.substring(0, 500) + '...',
            url: window.location.href
        };
        
        if (navigator.share) {
            navigator.share(shareData).catch(console.error);
        } else {
            // Fallback
            copyToClipboard();
            alert('Share not supported. Link copied to clipboard!');
        }
    }
    
    function copyToClipboard() {
        const content = document.getElementById('aiSummaryContent').innerText;
        navigator.clipboard.writeText(content).then(() => {
            // Show temporary success message
            const btn = event.target;
            const originalText = btn.innerHTML;
            btn.innerHTML = '<i class="bi bi-check-lg me-1"></i>Copied!';
            setTimeout(() => {
                btn.innerHTML = originalText;
            }, 2000);
        }).catch(err => {
            console.error('Copy failed:', err);
            alert('Failed to copy to clipboard');
        });
    }
    
    // Add smooth scrolling
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    });
</script>
@endpush
@endsection